# Generated by Django 4.1.7 on 2023-03-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(default=0, max_length=25, null=True)),
                ('room_number', models.CharField(max_length=100)),
                ('subjects', models.TextField()),
            ],
        ),
    ]
